# Generated by Django 4.2.5 on 2023-10-09 15:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("provider", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("AWARD", "Award"), ("CERTIFICATE", "Certificate")],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=40)),
                (
                    "course_type",
                    models.CharField(
                        choices=[("BACHELOR", "Bachelor"), ("OTHER", "Other")],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("institution_name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                ("until_present", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, default="", null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("birthdate", models.DateField()),
                ("nationality", models.CharField(max_length=30)),
                (
                    "languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30), size=None
                    ),
                ),
                (
                    "stack",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30), size=None
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "pronoums",
                    models.CharField(blank=True, default="he/him", max_length=13),
                ),
                ("nickname", models.CharField(blank=True, default="", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("short_description", models.CharField(max_length=40)),
                ("year", models.IntegerField()),
                ("image", models.ImageField(upload_to="images/")),
                ("is_favorite", models.BooleanField(default=False)),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("username", models.CharField(max_length=30, null=True)),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                (
                    "stack",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=15), size=None
                    ),
                ),
                ("description", models.TextField()),
                ("company_name", models.CharField(max_length=30)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("until_present", models.BooleanField(default=False)),
            ],
        ),
    ]
