# Generated by Django 4.2.5 on 2023-09-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_award_certificate_education_project_sociallink_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="type",
            field=models.CharField(
                choices=[("AWARD", "Award"), ("CERTIFICATE", "Certificate")],
                default="AWARD",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="education",
            name="course_type",
            field=models.CharField(
                choices=[("BACHELOR", "Bachelor"), ("OTHER", "Other")],
                default="other",
                max_length=30,
            ),
        ),
    ]
