# Generated by Django 4.2.5 on 2023-09-19 01:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_award_type_alter_education_course_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Certificate",
        ),
    ]
