# Generated by Django 4.2.5 on 2023-09-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_delete_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
