# Generated by Django 4.2.5 on 2023-09-23 16:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_person_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="pronoums",
            field=models.CharField(blank=True, default="he/him", max_length=13),
        ),
        migrations.AddField(
            model_name="work",
            name="stack",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=15), default=[""], size=None
            ),
            preserve_default=False,
        ),
    ]
