# Generated by Django 4.2.5 on 2023-09-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_person_pronoums_work_stack"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="skills",
            new_name="stack",
        ),
        migrations.AddField(
            model_name="person",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
