# Generated by Django 4.2.5 on 2023-09-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_skills_person_stack_person_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="end_date",
            field=models.DateField(null=True),
        ),
    ]
