# Generated by Django 4.2.5 on 2023-09-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_work_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
