# Generated by Django 4.2.5 on 2023-09-25 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_work_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sociallink",
            name="icon",
        ),
    ]
