# Generated by Django 4.2.5 on 2023-09-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_sociallink_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="username",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="url",
            field=models.URLField(null=True),
        ),
    ]
