# Generated by Django 4.2.5 on 2023-09-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_sociallink_username_alter_sociallink_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
