# Generated by Django 4.2.5 on 2023-09-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_sociallink_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
