# Generated by Django 4.2.5 on 2023-09-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_sociallink_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="award",
            name="provider",
            field=models.CharField(max_length=50),
        ),
    ]
