# Generated by Django 4.2.5 on 2023-10-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_award_name_alter_award_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
