# Generated by Django 4.2.5 on 2023-10-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_education_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
