version: '3'

services:

  db:
    image: postgres
    container_name: ckkwebsite_db
    volumes:
      - ckkwebsite_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./ckkwebsite/.env
    networks:
      - ckkwebsite_network
    expose:
      - 5432
    restart: always

  web:
    build: .
    container_name: ckkwebsite_app
    command: make run
    volumes:
      - ./ckkwebsite:/app/
      - staticfiles:/app/static/
      - mediafiles:/app/media/
    expose:
      - 8000
    env_file:
      - ./ckkwebsite/.env
    depends_on:
      - db
    links:
      - db:ckkwebsite_db
    networks:
      - ckkwebsite_network
    restart: always

  nginx:
    build: ./ngnix/
    container_name: ckkwebsite_ngnix
    volumes:
      - staticfiles:/app/static/
      - mediafiles:/app/media/
    ports:
      - 8008:80
    depends_on:
      - web
    networks:
      - ckkwebsite_network

networks:
  ckkwebsite_network:
    driver: bridge

volumes:
  ckkwebsite_postgres_data:
  staticfiles:
  mediafiles:
