name: Docker Compose Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VPS
        uses: appleboy/ssh-action@v0.4.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}

      - name: Get new changes, rebuild and run Docker Compose on VPS
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /home/git/ckk-boring-website/ && git pull'
          ssh -i ${{ secrets.VPS_SSH_KEY }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "docker compose -f /home/git/ckk-boring-website/docker-compose.yml up -d --build"
          
