name: Docker Compose Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VPS 
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: ${{ secrets.VPS_USERNAME }}
          REMOTE_PORT: 22  
          SCRIPT_AFTER: |
            cd /home/git/ckk-boring-website/ && git pull
            docker compose -f /home/git/ckk-boring-website/docker-compose.yml up -d --build
        
